spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furnitureDB
    username: root
    password: 08146587069Gg@

#twilio:
#  account-sid: ACdecb8941842d15a54dc480cc153eb662
#  auth-token: 36caaf72b0088816974ff88f804187a8
#  from-phone-number: +15075967416

mail:
  api:
    key: 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
sendinblue:
  mail:
    url: https://api.brevo.com/v3/emailCampaigns

cloudinary:
  cloud:
    name: martins-o
  api:
    secret: rco0un61BRlpULBBUzlitm0aWhU
    key: 432922932255442

#jwt:
#  secret:
#    key: D8FCF71D41352CD49FDD2762BEB69
#security:
#  constants:
#    jwt-secret: D8FCF71D41352CD49FDD2762BEB69
#    jwt-exp-time: 60